[[validator]]
restartable = true
sync_mode = "full"

[[validator]]
restartable = true
sync_mode = "full"

[[validator]]
restartable = true
sync_mode = "history"

[[validator]]
restartable = true
sync_mode = "full"

[[spammer]]
restartable = false
sync_mode = "history"
profile = "spammer/src/spammer_default.toml"

[[seed]]
restartable = false
sync_mode = "history"
