[package]
name = "nimiq-zkp-primitives"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true
description = "Shared Primitives of Recursive SNARKs for Nimiq's Nano Nodes"
homepage.workspace = true
repository.workspace = true
categories.workspace = true
keywords.workspace = true

[lints]
workspace = true

[dependencies]
ark-crypto-primitives = { version = "0.5", features = ["crh"] }
ark-ec = "0.4"
ark-ff = "0.4"
ark-groth16 = { version = "0.5", default-features = false }
ark-mnt4-753 = "0.5"
ark-mnt6-753 = "0.5"
ark-relations = "0.5"
ark-r1cs-std = "0.4"
ark-serialize = "0.5"
ark-std = "0.5"
hex = "0.4"
log = { workspace = true }
rand = { version = "0.9", features = ["small_rng"] }
rayon = { version = "^1.10", optional = true }
serde = { version = "1.0" }
thiserror = "2.0"

nimiq-bls = { workspace = true }
nimiq-hash = { workspace = true }
nimiq-pedersen-generators = { workspace = true }
nimiq-primitives = { workspace = true, features = ["policy"] }
nimiq-serde = { workspace = true }

[dev-dependencies]
nimiq-collections = { workspace = true }
nimiq-keys = { workspace = true }
nimiq-primitives = { workspace = true, features = ["slots"] }
nimiq-utils = { workspace = true }

[features]
parallel = [
    "rayon",
    "ark-ec/parallel",
    "ark-ff/parallel",
    "ark-std/parallel",
    "ark-groth16/parallel",
    "nimiq-primitives/parallel",
]
zkp-prover = [
    "ark-crypto-primitives/r1cs",
    "ark-mnt4-753/r1cs",
    "ark-mnt6-753/r1cs",
    "ark-groth16/r1cs",
    "nimiq-primitives/zkp-prover",
]
