[package]
name = "nimiq-transaction-builder"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true
description = "Wallet logic for Nimiq's Rust implementation"
homepage.workspace = true
repository.workspace = true
categories.workspace = true
keywords.workspace = true

[badges]
travis-ci = { repository = "nimiq/core-rs", branch = "master" }
maintenance = { status = "experimental" }

[lints]
workspace = true

[dependencies]
serde = { version = "1.0", optional = true }
thiserror = "2.0"

nimiq-bls = { workspace = true }
nimiq-hash = { workspace = true }
nimiq-keys = { workspace = true }
nimiq-primitives = { workspace = true }
nimiq-serde = { workspace = true }
nimiq-transaction = { workspace = true }

[dev-dependencies]
hex = "0.4"
rand = "0.8"

nimiq-test-log = { workspace = true }
nimiq-utils = { workspace = true, features = ["otp", "key-rng"]}


[features]
serde-derive = ["serde", "nimiq-primitives/serde-derive"]
