[package]
name = "nimiq-macros"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true
description = "Macros for Nimiq's Rust implementation"
homepage.workspace = true
repository.workspace = true
categories.workspace = true
keywords.workspace = true

[lints]
workspace = true

[dependencies]
hex = "0.4"
serde = "1.0"
subtle = "2.6"

nimiq-serde = { workspace = true }

[badges]
travis-ci = { repository = "nimiq/core-rs", branch = "master" }
is-it-maintained-issue-resolution = { repository = "nimiq/core-rs" }
is-it-maintained-open-issues = { repository = "nimiq/core-rs" }
maintenance = { status = "experimental" }
