name: Publish web-client to npm
on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown
      - uses: Swatinem/rust-cache@v2
      - name: Build package
        working-directory: ./web-client
        run: ./scripts/build.sh
      - uses: actions/setup-node@v4
        with:
          registry-url: 'https://registry.npmjs.org'
      - name: Publish to npm
        working-directory: ./web-client/dist
        run: npm publish --provenance
        env:
          NODE_AUTH_TOKEN: ${{ secrets.SISOU_NPM_TOKEN }}
